name: Somerset Artists
favicon: null
layout_spectrum: 0.7890826710499823
typography_spectrum: 0.9222487537190318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040d16'
    - '#6698af'
    - '#4c4a4d'
    - '#857566'
    - '#672d4b'
  brandStrength: 0.33366143167950213
  lightness: 0.01950192148797214
  saturation: 0.4299215874634683
  rhythmicContrast: 0.8674810843076557
purpose: []
